### ISSUE TITLE
dataset_description.json missing

### ISSUE THREAD

**Issue by effigies** [psychoinformatics-de/studyforrest-data-structural#3]
This dataset can be parsed with PyBIDS' `BIDSLayout` but only with `validate=False`, else 

```
BIDSValidationError: 'dataset_description.json' is missing from project root. Every valid BIDS dataset must have this file.
Example contents of 'dataset_description.json': 
{"Name": "Example dataset", "BIDSVersion": "1.0.2"}
```

**Comment by adswa** [comment]
Thanks (and sorry no-one has seen that yet)! We're hacking on harmonizing and getting studyforrest data in shape in the last week of April, I'll add it to the TODO list. :+1:
